version: "3.5"

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3308:3306
    volumes:
      - my_db_data:/var/lib/mysql

volumes:
  my_db_data:
